### ISSUE TITLE
Script execution failed due to missing deployment

### ISSUE THREAD

**Issue by brnaba-aws** [awslabs/aws-greengrass-labs-component-for-the-things-stack-lorawan#5] opened 2021-12-14 12:46 UTC
When following the readme, the quickstart.sh script failed as it is expecting a deployment to be already created in the aws account. In order to bypass this problem, you need to create a deployment following this pattern: Deployment for <thingName>

**Comment by gregbreen** [comment] 2021-12-15 02:37
Thanks @brnaba-aws . The problem is in the deploy_component_version.py script, when the expected deployment name does not already exist. I will soon fix it.

In the meantime, besides creating a deployment with a name that matches its demands, you can also just do all of your deployments using the Console or CLI. The deploy_component_version.py script is a convenience only. Its main benefit is it sets up the configuration of the Secret Manager component; you can of course do this yourself from the console or CLI.

**Comment by pallavi03** [comment] 2022-02-08 19:06
Closing the issue as code is merged

**Closed by pallavi03** 2022-02-08 19:06 UTC
